### ISSUE TITLE
Issue with changing light color

### ISSUE THREAD

**Issue by lorek123** [xaviml/z2m_ikea_controller#2]
I'm connecting LED1624G9 and E1524/E1810 via Zigbee2mqtt 1.70. Toggling light and switching brightness works ok, but when I'm trying to change color it fails:
```
2019-12-01 13:39:00.355232 WARNING AppDaemon: ------------------------------------------------------------
2019-12-01 13:39:00.359574 WARNING AppDaemon: ------------------------------------------------------------
2019-12-01 13:39:00.359790 WARNING AppDaemon: Unexpected error in worker for App smallroom_light:
2019-12-01 13:39:00.360030 WARNING AppDaemon: Worker Ags: {'name': 'smallroom_light', 'id': UUID('2e48a534-872d-4309-adb9-9a96315ab91d'), 'type': 'attr', 'function': <bound method IkeaController.state of <z2m_ikea_controller.E1810Controller object at 0x7fc7f82df748>>, 'attribute': 'state', 'entity': 'sensor.0x90fd9ffffedc7ddd_action', 'new_state': 'arrow_right_click', 'old_state': 'arrow_right_click', 'kwargs': {'handle': UUID('05ae5341-804c-40ce-aba9-d777a16f787e')}}
2019-12-01 13:39:00.360199 WARNING AppDaemon: ------------------------------------------------------------
2019-12-01 13:39:00.360612 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 595, in worker
    self.sanitize_state_kwargs(app, args["kwargs"]))
  File "/conf/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 70, in state
    self.turn_on_light(attribute, value, sign, self.manual_steps)
  File "/conf/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 96, in turn_on_light
    new_state_attribute = old + sign * step
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

2019-12-01 13:39:00.360769 WARNING AppDaemon: ------------------------------------------------------------

```

apps.yaml:
```
/conf/apps/apps.yaml
hello_world:
  module: hello
  class: HelloWorld
smallroom_light:
  module: z2m_ikea_controller
  class: E1810Controller
  sensor: "sensor.0x90fd9ffffedc7ddd_action"
  light: "light.0x90fd9ffffef3826c_light"
```

**Comment by xaviml** [comment]
The code right now just uses the following light attributes: "brightness" and "color_temp". Your light is not changing the color since LED1624G9 does not support the color temperature (color_temp) attribute, just the xy_color. I see two solutions for this:

* Convert from colot_temp to xy_color. This conversion can be found in the [util](https://github.com/home-assistant/home-assistant/blob/master//homeassistant/util/color.py) from home assistant. However, I think it is not possible to access to home assistant util from appdaemon.

* Pass two colors through parameters and go from one color to another one in a gradient step.

I see the second solution more feasible for this use case.

**Comment by lorek123** [comment]
Let me know how I can help, I could try to code that if there is an example I could use

**Comment by ginodp** [comment]
Same problem here.
Color change not working.
Hope there will be a fix.

**Comment by xaviml** [comment]
Hi @lorek123 and @ginodp,

I updated the code and now it supports color for the lights that have xy_color attribute. I haven't released the code yet, but you can copy and paste the code from the master branch and let me know if this works for you. I now have the LED1624G9 and it worked on my end.

I updated the README file with the color feature. By default, it checks if the light supports xy_color, otherwise it will use color_temp. So if the light supports xy_color when the arrows are pressed, it does a loop of colors until the button is released.

Thank you for your support and let me know if it works as expected to close this issue.

**Comment by ginodp** [comment]
I will be home in 3 hours and will test if it's working. I'll let u know soon. Thanks in advance for your great work.

**Comment by ginodp** [comment]
I copied the "Master" -> "z2m_ikea_controller/apps/z2m_ikea_controller/z2m_ikea_controller.py"

2020-01-06 17:00:11.412622 INFO AppDaemon: Reading config
2020-01-06 17:00:11.425675 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-06 17:00:11.426296 INFO AppDaemon: App 'ikea_light_dressoir' changed
2020-01-06 17:00:11.427986 INFO AppDaemon: Terminating ikea_light_dressoir
2020-01-06 17:00:11.428930 INFO AppDaemon: Initializing app ikea_light_dressoir using class E1810Controller from module z2m_ikea_controller
2020-01-06 17:00:11.429867 WARNING AppDaemon: ------------------------------------------------------------
2020-01-06 17:00:11.430430 WARNING AppDaemon: Unexpected error running initialize() for ikea_light_dressoir
2020-01-06 17:00:11.430930 WARNING AppDaemon: ------------------------------------------------------------
2020-01-06 17:00:11.432440 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 200, in initialize
    super().initialize()
  File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 98, in initialize
    super().initialize()
  File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 50, in initialize
    self.actions_mapping = {
  File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 53, in <dictcomp>
    if key in included_actions
TypeError: argument of type 'NoneType' is not iterable
2020-01-06 17:00:11.433036 WARNING AppDaemon: ------------------------------------------------------------

**Comment by xaviml** [comment]
Sorry @ginodp, it should be fixed now. Let me know about it.

**Comment by ginodp** [comment]
Very nice it works like a charm.

Can I add more colors to it? Like white!

**Comment by xaviml** [comment]
Perfect! We could add white near the light blue so it blends a little bit. If you open the dialog of the light on home assistant, you will see it goes over the whole circle, but not the middle, which is the middle.

**Comment by ginodp** [comment]
I added the white color before blue starts for the blend.

        (0.141, 0.137),
        (0.146, 0.238),
        (0.323, 0.329),# white color middle
        (0.151, 0.343),
        (0.157, 0.457),

Works nicely. This middle color is a nice warm color next to the white from blue.

**Comment by xaviml** [comment]
Thanks @ginodp. I will add the color and let you know about it.

**Comment by xaviml** [comment]
Hey @ginodp,

I just add the white color as you said, the color blends in quite well. You can download the last version for it.
